version: '3.8'

services:
  be:
    container_name: tsel-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    env_file:
      - .env

  # db:
  #   container_name: tsel-db
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - '5435:5432'
  #   restart: unless-stopped
# volumes:
#   postgres_data:
